import Footer from "@/layouts/Footer";
import Header from "@/layouts/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }: LayoutProps<"/">) {
  return (
    <div>
        <Header/>
        {children}
        <Footer/>
    </div>
  );
}